CREATE TABLE IF NOT EXISTS `nw_playreward` (
    `identifier` VARCHAR(80) NOT NULL,
    `online_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
    `claimed` LONGTEXT NULL,
    `last_reset` INT UNSIGNED NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
